import type { ModelMeta } from '@zglm/shared';

export const MODEL_CATALOG: Record<string, ModelMeta> = {
  'glm-5': {
    id: 'glm-5',
    displayName: 'GLM-5',
    family: 'glm-5',
    params: '744B (40B active)',
    contextWindow: 200_000,
    maxOutput: 128_000,
    inputPrice: 5.00,
    outputPrice: 20.00,
    capabilities: ['text', 'code', 'vision', 'function-calling', 'web-search', 'thinking', 'streaming'],
    tier: 'premium',
    supportsThinking: true,
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: true,
    recommended: 'agent',
  },
  'glm-5-turbo': {
    id: 'glm-5-turbo',
    displayName: 'GLM-5 Turbo',
    family: 'glm-5',
    params: '744B (40B active)',
    contextWindow: 205_000,
    maxOutput: 128_000,
    inputPrice: 3.00,
    outputPrice: 15.00,
    capabilities: ['text', 'code', 'function-calling', 'web-search', 'thinking', 'streaming'],
    tier: 'premium',
    supportsThinking: true,
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: true,
    recommended: 'coding',
  },
  'glm-5v-turbo': {
    id: 'glm-5v-turbo',
    displayName: 'GLM-5V Turbo',
    family: 'glm-5',
    params: '744B (40B active)',
    contextWindow: 200_000,
    maxOutput: 128_000,
    inputPrice: 4.00,
    outputPrice: 16.00,
    capabilities: ['text', 'code', 'vision', 'function-calling', 'web-search', 'thinking', 'streaming'],
    tier: 'premium',
    supportsThinking: true,
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: true,
    recommended: 'vision',
  },
  'glm-4.7': {
    id: 'glm-4.7',
    displayName: 'GLM-4.7',
    family: 'glm-4',
    params: '~400B',
    contextWindow: 200_000,
    maxOutput: 128_000,
    inputPrice: 1.50,
    outputPrice: 6.00,
    capabilities: ['text', 'code', 'function-calling', 'web-search', 'streaming'],
    tier: 'standard',
    supportsThinking: false,
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: true,
  },
  'glm-4.6': {
    id: 'glm-4.6',
    displayName: 'GLM-4.6',
    family: 'glm-4',
    params: '355B (32B active)',
    contextWindow: 200_000,
    maxOutput: 128_000,
    inputPrice: 1.00,
    outputPrice: 4.00,
    capabilities: ['text', 'code', 'function-calling', 'web-search', 'streaming'],
    tier: 'standard',
    supportsThinking: false,
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: true,
  },
  'glm-4.5': {
    id: 'glm-4.5',
    displayName: 'GLM-4.5',
    family: 'glm-4',
    params: '355B (32B active)',
    contextWindow: 128_000,
    maxOutput: 16_384,
    inputPrice: 0.80,
    outputPrice: 3.20,
    capabilities: ['text', 'code', 'function-calling', 'web-search', 'streaming'],
    tier: 'standard',
    supportsThinking: false,
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: true,
    recommended: 'fast',
  },
  'glm-4.5-air': {
    id: 'glm-4.5-air',
    displayName: 'GLM-4.5 Air',
    family: 'glm-4',
    params: '106B (12B active)',
    contextWindow: 128_000,
    maxOutput: 16_384,
    inputPrice: 0.30,
    outputPrice: 1.20,
    capabilities: ['text', 'code', 'function-calling', 'streaming'],
    tier: 'standard',
    supportsThinking: false,
    supportsVision: false,
    supportsTools: true,
    supportsWebSearch: false,
    recommended: 'economy',
  },
  'glm-4.5-flash': {
    id: 'glm-4.5-flash',
    displayName: 'GLM-4.5 Flash',
    family: 'glm-4',
    params: '-',
    contextWindow: 128_000,
    maxOutput: 4_096,
    inputPrice: 0.00,
    outputPrice: 0.00,
    capabilities: ['text', 'code', 'streaming'],
    tier: 'free',
    supportsThinking: false,
    supportsVision: false,
    supportsTools: false,
    supportsWebSearch: false,
    recommended: 'economy',
  },
  'glm-4.6v': {
    id: 'glm-4.6v',
    displayName: 'GLM-4.6V',
    family: 'glm-4',
    params: '106B',
    contextWindow: 128_000,
    maxOutput: 16_384,
    inputPrice: 1.20,
    outputPrice: 4.80,
    capabilities: ['text', 'code', 'vision', 'function-calling', 'streaming'],
    tier: 'standard',
    supportsThinking: false,
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: false,
    recommended: 'vision',
  },
  'glm-4.5v': {
    id: 'glm-4.5v',
    displayName: 'GLM-4.5V',
    family: 'glm-4',
    params: '106B',
    contextWindow: 64_000,
    maxOutput: 4_096,
    inputPrice: 1.00,
    outputPrice: 4.00,
    capabilities: ['text', 'code', 'vision', 'function-calling', 'streaming'],
    tier: 'standard',
    supportsThinking: false,
    supportsVision: true,
    supportsTools: true,
    supportsWebSearch: false,
    recommended: 'vision',
  },
};

export const MODEL_IDS = Object.keys(MODEL_CATALOG);

export const DEFAULT_MODEL = 'glm-4.6';

export function getModelMeta(modelId: string): ModelMeta | undefined {
  return MODEL_CATALOG[modelId];
}

export function getModelsByTier(tier: ModelMeta['tier']): ModelMeta[] {
  return Object.values(MODEL_CATALOG).filter((m) => m.tier === tier);
}
